/*
 * generated by Xtext 2.32.0-SNAPSHOT
 */
package org.eclipse.xpect.ui;

import com.google.inject.Injector;
import org.eclipse.xpect.ui.internal.XpectActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XpectExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XpectActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XpectActivator activator = XpectActivator.getInstance();
		return activator != null ? activator.getInjector(XpectActivator.ORG_ECLIPSE_XPECT_XPECT) : null;
	}

}
