/*
 * generated by Xtext 2.32.0-SNAPSHOT
 */
package org.eclipse.xpect.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xpect.parser.antlr.internal.InternalXpectParser;
import org.eclipse.xpect.services.XpectGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XpectParser extends AbstractAntlrParser {

	@Inject
	private XpectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	

	@Override
	protected InternalXpectParser createParser(XtextTokenStream stream) {
		return new InternalXpectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "XpectFile";
	}

	public XpectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XpectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
