/*
 * generated by Xtext
 */
package org.eclipse.xpect.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xpect.services.XpectGrammarAccess;

public class XpectParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XpectGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected org.eclipse.xpect.parser.antlr.internal.InternalXpectParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xpect.parser.antlr.internal.InternalXpectParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XpectFile";
	}
	
	public XpectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XpectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
