/*
 * generated by Xtext 2.32.0-SNAPSHOT
 */
package org.eclipse.xpect.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXpectScopeProvider extends DelegatingScopeProvider {
}
