/*
 * generated by Xtext 2.9.2
 */
package org.eclipse.xpect.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class XpectValidator extends AbstractXpectValidator {
	
//  public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					XpectPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
